### ISSUE TITLE
Crash on tintColorDidChange

### ISSUE THREAD

**Issue by skorulis** [kreeger/BDKCollectionIndexView#11] opened 2015-02-20 04:08 UTC
I'm seeing the following crash occasionally in hockey app. I'm not sure how it's happening or why it's only just started occurring. I've been using :head in my podfile so maybe a recent change has caused it.

- [BDKCollectionIndexView tintColorDidChange]
in BDKCollectionIndexView.m, line 132
Info: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setTextColor:]: unrecognized selector sent to instance 0x1741956e0'

I think the problem is caused by the touchStatusView being in the hierarchy but not being a UILabel but I can't confirm this.

**Comment by kreeger** [comment] 2015-02-20 04:11
Thanks for raising this; I have a feeling this was caused by https://github.com/kreeger/BDKCollectionIndexView/pull/8.

Would you be able to submit a fix? If not, I'll try to look into this this weekend.

**Comment by skorulis** [comment] 2015-02-20 04:15
Put up a very small pull request which should solve the immediate problem by putting in a type check. Not sure if you want to try and do something more elegant.

**Comment by kreeger** [comment] 2015-04-10 02:22
Fixed with a recent merge; closing issue.

**Closed by kreeger** 2015-04-10 02:22 UTC
